### ISSUE TITLE
The points (at least GPs) are adding up after rollback

### ISSUE THREAD

**Issue by antivirak** [antivirak/japonsko-vn#27]
![image](https://github.com/antivirak/japonsko-vn/assets/56031501/ded5949b-bc97-4b64-83f7-18d0f00e8ddc)
You can farm points by using back button

**Comment by Elerenard** [comment]
<img width="497" alt="Snímek obrazovky 2024-07-01 223537" src="https://github.com/antivirak/japonsko-vn/assets/173553173/6c50cb84-26ed-482c-bef0-f49d72c61f7d">
